[fix] job1, 2
- 개행 수정

diff --git a/.github/workflows/assignment-6-ci.yml b/.github/workflows/assignment-6-ci.yml
--- a/.github/workflows/assignment-6-ci.yml
+++ b/.github/workflows/assignment-6-ci.yml
@@ -24,10 +24,10 @@ jobs:
         id: job1
         run: |
           if ! output=$(pnpm -F assignment-6 install 2>&1 && pnpm -F assignment-6 build 2>&1); then
-          echo "error<<EOF" >> $GITHUB_OUTPUT
-          echo "$output" >> $GITHUB_OUTPUT
-          echo "EOF" >> $GITHUB_OUTPUT
-          exit 1
+            echo "error<<EOF" >> $GITHUB_OUTPUT
+            echo "$output" >> $GITHUB_OUTPUT
+            echo "EOF" >> $GITHUB_OUTPUT
+            exit 1
           fi
       - name: Comment PR on Failure
         if: failure()
