[fix] job1, 2
- 멀티라인 출력을 올바르게 처리하고 $GITHUB_OUTPUT에 쓰기 위해 수정

diff --git a/.github/workflows/assignment-6-ci.yml b/.github/workflows/assignment-6-ci.yml
--- a/.github/workflows/assignment-6-ci.yml
+++ b/.github/workflows/assignment-6-ci.yml
@@ -23,7 +23,12 @@ jobs:
       - name: 'job1: tsc, build 를 실행한다. 오류가 발생하면 코멘트를 남긴다.'
         id: job1
         run: |
-          output=$(pnpm -F assignment-6 install 2>&1 && pnpm -F assignment-6 build 2>&1) || echo "error"="$output" >> $GITHUB_OUTPUT
+          if ! output=$(pnpm -F assignment-6 install 2>&1 && pnpm -F assignment-6 build 2>&1); then
+          echo "error<<EOF" >> $GITHUB_OUTPUT
+          echo "$output" >> $GITHUB_OUTPUT
+          echo "EOF" >> $GITHUB_OUTPUT
+          exit 1
+          fi
       - name: Comment PR on Failure
         if: failure()
         uses: actions/github-script@v7
@@ -58,7 +63,12 @@ jobs:
       - name: 'job2: eslint를 실행한 다음에, eslint에서 오류가 발생할 경우 report를 코멘트에 남긴다.'
         id: job2
         run:  |
-          output=$(pnpm -F assignment-6 install 2>&1 && pnpm -F assignment-6 lint 2>&1) || echo "error"="$output" >> $GITHUB_OUTPUT
+          if ! output=$(pnpm -F assignment-6 install 2>&1 && pnpm -F assignment-6 lint 2>&1); then
+            echo "error<<EOF" >> $GITHUB_OUTPUT
+            echo "$output" >> $GITHUB_OUTPUT
+            echo "EOF" >> $GITHUB_OUTPUT
+            exit 1
+          fi
       - name: Comment PR on Failure
         if: failure()
         uses: actions/github-script@v7
