lighthouse

diff --git a/.github/workflows/assignment-6-ci.yml b/.github/workflows/assignment-6-ci.yml
--- a/.github/workflows/assignment-6-ci.yml
+++ b/.github/workflows/assignment-6-ci.yml
@@ -125,9 +125,28 @@ jobs:
   lighthouse:
     runs-on: ubuntu-latest
     steps:
-      - name: job4 구현
-        run: echo "job4의 내용을 구현해주세요"
+      - name: Check out
+        uses: actions/checkout@v4
 
+      - name: Install pnpm
+        uses: pnpm/action-setup@v2
+        with:
+          version: 8
+
+      - name: Setup Node.js environment
+        uses: actions/setup-node@v4
+        with:
+          node-version: 20
+          cache: "pnpm"
+      
+      - name: Build
+        run: pnpm --filter assignment-6 build
+
+      - name: Run Lighthouse ci
+        run: |
+          pnpm install -g @lhci/cli
+          lhci autorun || echo "Fail to Run Lighthouse CI"
+          
   assign_reviewer:
     runs-on: ubuntu-latest
     steps:
