chore : pnpm lhci cli

diff --git a/.github/workflows/assignment-6-ci.yml b/.github/workflows/assignment-6-ci.yml
--- a/.github/workflows/assignment-6-ci.yml
+++ b/.github/workflows/assignment-6-ci.yml
@@ -95,10 +95,11 @@ jobs:
         run: pnpm install
 
       - name: Run Lighthouse CI
+        run: |
+          pnpm i -g @lhci/cli
+          pnpm -F assignment-6 lhci autorun || echo "Fail to Run Lighthouse CI!"
         env:
           LHCI_GITHUB_APP_TOKEN: ${{secrets.TOKEN_FOR_CI}}
-        run: |
-          pnpm -F assignment-6 lhci autorun || echo "Fail to Run Lighthouse CI!"
 
   assign_reviewer:
     runs-on: ubuntu-latest
