lint관련 수정

diff --git a/.github/workflows/assignment-6-ci.yml b/.github/workflows/assignment-6-ci.yml
--- a/.github/workflows/assignment-6-ci.yml
+++ b/.github/workflows/assignment-6-ci.yml
@@ -70,21 +70,21 @@ jobs:
       - name: Install dependencies
         run: pnpm install
       - name: Run ESLint
-        run: pnpm -F assignment-6 lint
-        continue-on-error: true
+        run: pnpm -F assignment-6 run lint > lint_results.txt || true
+        working-directory: packages/assignment-6
       - name: Comment ESLint result
         if: failure()
         uses: actions/github-script@v7
         with:
           github-token: ${{secrets.TOKEN_FOR_CI}}
           script: |
-            const fs = require('fs')
-            const eslintReport = fs.readFileSync('.eslintrc.json', 'utf8')
+            const fs = require('fs');
+            const lintResults = fs.readFileSync('packages/assignment-6/lint_results.txt', 'utf8');
             github.rest.issues.createComment({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
-              body: `## ESLint FAIL ❌ \n ${eslintReport.trim()}`
+              body: `## ESLint FAIL ❌ \n ${lintResults}`
             })
 
   test:
