[fix] job1, 2
- output 설정

diff --git a/.github/workflows/assignment-6-ci.yml b/.github/workflows/assignment-6-ci.yml
--- a/.github/workflows/assignment-6-ci.yml
+++ b/.github/workflows/assignment-6-ci.yml
@@ -23,8 +23,7 @@ jobs:
       - name: 'job1: tsc, build 를 실행한다. 오류가 발생하면 코멘트를 남긴다.'
         id: job1
         run: |
-          pnpm -F assignment-6 install
-          pnpm -F assignment-6 build
+          output=$(pnpm -F assignment-6 install 2>&1 && pnpm -F assignment-6 build 2>&1) || echo "::set-output name=error::$output"
       - name: Comment PR on Failure
         if: failure()
         uses: actions/github-script@v7
@@ -33,7 +32,9 @@ jobs:
           script: |
             const jobOutput = `${process.env.GITHUB_WORKFLOW} 워크플로우의 job1 단계에서 오류가 발생했습니다:
             
-            ${{ steps.job1.outputs.stderr }}
+            \`\`\`
+            ${{ steps.job1.outputs.error }}
+            \`\`\`
             `
             
             github.rest.issues.createComment({
@@ -57,8 +58,7 @@ jobs:
       - name: 'job2: eslint를 실행한 다음에, eslint에서 오류가 발생할 경우 report를 코멘트에 남긴다.'
         id: job2
         run:  |
-          pnpm -F assignment-6 install
-          pnpm -F assignment-6 lint
+          output=$(pnpm -F assignment-6 install 2>&1 && pnpm -F assignment-6 lint 2>&1) || echo "::set-output name=error::$output"
       - name: Comment PR on Failure
         if: failure()
         uses: actions/github-script@v7
@@ -67,7 +67,9 @@ jobs:
           script: |
             const jobOutput = `${process.env.GITHUB_WORKFLOW} 워크플로우의 job2 단계에서 오류가 발생했습니다:
             
+            \`\`\`
             ${{ steps.job2.outputs.stderr }}
+            \`\`\`
             `
             
             github.rest.issues.createComment({
