[fix] job1, 2
- set-output -> GITHUB_OUTPUT 변경
  - https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

diff --git a/.github/workflows/assignment-6-ci.yml b/.github/workflows/assignment-6-ci.yml
--- a/.github/workflows/assignment-6-ci.yml
+++ b/.github/workflows/assignment-6-ci.yml
@@ -23,7 +23,7 @@ jobs:
       - name: 'job1: tsc, build 를 실행한다. 오류가 발생하면 코멘트를 남긴다.'
         id: job1
         run: |
-          outputs=$(pnpm -F assignment-6 install 2>&1 && pnpm -F assignment-6 build 2>&1) || echo "::set-output name=error::$output"
+          output=$(pnpm -F assignment-6 install 2>&1 && pnpm -F assignment-6 build 2>&1) || echo "error"="$output" >> $GITHUB_OUTPUT
       - name: Comment PR on Failure
         if: failure()
         uses: actions/github-script@v7
@@ -58,7 +58,7 @@ jobs:
       - name: 'job2: eslint를 실행한 다음에, eslint에서 오류가 발생할 경우 report를 코멘트에 남긴다.'
         id: job2
         run:  |
-          outputs=$(pnpm -F assignment-6 install 2>&1 && pnpm -F assignment-6 lint 2>&1) || echo "::set-output name=error::$output"
+          output=$(pnpm -F assignment-6 install 2>&1 && pnpm -F assignment-6 lint 2>&1) || echo "error"="$output" >> $GITHUB_OUTPUT
       - name: Comment PR on Failure
         if: failure()
         uses: actions/github-script@v7
